2024.6 Bitwarden uses camelCase keys instead of PascalCase
corpusops/bitwardentools pull request #29
Opened 2024-07-17 07:39 UTC by OdyX

This fixes client access to a 2024.6 Vaultwarden instance.

2024-07-22 10:43 UTC, commonism requested changes

2024-07-22 10:43 UTC, commonism commented on src/bitwardentools/client.py
>                      typ = jsond["Type"]
missing - type

2024-07-22 10:43 UTC, commonism commented on src/bitwardentools/client.py
>                      typ = jsond["Type"]
below - L.error(f'Unkown cipher {jsond.get("Id", "")}') 
needs to be "id"

2024-07-22 10:52 UTC, commonism commented on src/bitwardentools/client.py
>                      typ = jsond["Type"]
To clarify, missed Type and Id in the related lines below.

2024-07-22 11:16 UTC, commonism commented
Required for Vaultwarden 1.31 released 08.07.2024

https://github.com/dani-garcia/vaultwarden/releases/tag/1.31.0
> Change API and structs to camelCase by @dani-garcia in https://github.com/dani-garcia/vaultwarden/pull/4386

2024-07-23 13:34 UTC, OdyX commented on src/bitwardentools/client.py
>                      typ = jsond["Type"]
Right; fixed.

2024-07-23 19:34 UTC, commonism commented
@kiorky - this needs your attention, all tooling using bitwarden tools is broken by the API changes and require these updates.

2024-08-16 07:04 UTC, commonism commented
Would you accept a patch which makes use of pydantic to process/validate the json?
pydantic is quite a dependency but … besides best in class validation it adds comfort.

e.g. - https://docs.pydantic.dev/latest/concepts/alias/

2024-12-12 21:01 UTC, kiorky commented
Hello, i want to thanks you very much as it largely inspired the latest release with my own fix !

2024-12-12 21:01 UTC, closed without merging